### ISSUE TITLE
built-in service names -- comments? documentation?

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/mantle#100]
https://github.com/oasislabs/mantle/blob/68aedb8cce8e1a56472bcc8fc222c478c5d5e583/bcfs/src/bcfs.rs#L362

what parts of the namespace is reserved?  are there plans for new services?

it might be nicer for this to be data-driven, i.e., via an indirection mechanism like major/minor device numbers for device files in unix-like systems, so that names aren't hardcoded into the source as strings in the code, but as initialization data of some kind (initial "disk image").

probably does not belong here, but was looking to see if "." and ".." components were being reserved.  not sure if there an intention to be as posix-like as feasible, but if so, these should be illegal.

**Comment by nhynes** [comment]
service sock has been removed. `.` will resolve and `..` will `ENOENT`.
