### ISSUE TITLE
pathbuf pop failure should be handled as staying at / for posix compatibility

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/mantle#136]
https://github.com/oasislabs/mantle/blob/980ec638245b5ee64b751280288bf7dd4e205076/bcfs/src/bcfs.rs#L385

for posix filesystems the `..` entry in `/` is `/` itself; this is the signal for having reached the root directory for a program such as `pwd` (or `getcwd(3)` library function), so for full compatibility, we shouldn't return `NoEnt` in `canonicalize_path`

**Comment by nhynes** [comment]
Also TODO:
* fix doc https://github.com/oasislabs/mantle/blob/master/bcfs/src/bcfs.rs#L536
* use fd_usize https://github.com/oasislabs/mantle/blob/master/bcfs/src/bcfs.rs#L144

**Comment by nhynes** [comment]
WASI directories are capabilities. Using `..` to access a directory above the directory passed into `path_open` would require a capability to that parent directory.
