### ISSUE TITLE
Api for new style contracts to call old style contracts

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/mantle#58]
`import_contract!(oldstyle_contract.json)` generates a client that can call old-style contracts using ethabi. Rust contracts already generate new-style clients.

Related: https://github.com/oasislabs/oasis-rs/issues/57

**Comment by armaniferrante** [comment]
@nhynes why is this needed for release 3?

**Comment by nhynes** [comment]
I recall us wanting to have backward compatibility with evm?

**Comment by armaniferrante** [comment]
We absolute do, but I'd advocate for us to punt this for release 3, where the bar for release 3 (in my mind) is things absolutely required for an MVP. 

@willscott thoughts?

**Comment by willscott** [comment]
cc @naheed 

if we can enable this after initial MVP without breaking existing semantics I would argue for fast follow / scoping this out of initial release since the complexity of feeling like we've tested this appropriately seems like it could be somewhat high

**Comment by naheed** [comment]
let's do this as release 4 high priority candidate.
