### ISSUE TITLE
oasis std doesn't indicate it's dependence on wasm-build

### ISSUE THREAD

**Issue by willscott** [oasislabs/mantle#87]
per @nhynes:
```
you're missing wasm-build. cargo install owasm-utils --bin wasm-build or something
```

if `wasm-build` is called by the oasis-std proc macro silently, then it needs to be a dependency that is installed or available to oasis-std, and not a separate binary.

also, shouldn't need to be separately globally installed.

**Comment by nhynes** [comment]
wasm-build is going to be replaced by oasis-build
